# Generated by Django 5.1.1 on 2024-09-17 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_student_enrollment_year_alter_student_student_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('department', models.CharField(choices=[('CS', 'Computer Science'), ('BI', 'Biology'), ('CH', 'Chemistry'), ('EN', 'English'), ('MA', 'Mathematics'), ('PH', 'Physics'), ('EC', 'Economics'), ('PS', 'Political Science'), ('HI', 'History'), ('ED', 'Education')], default='CS', max_length=2)),
                ('instructor', models.CharField(choices=[('Sarah Johnson', 'Dr. Sarah Johnson'), ('Michael Lee', 'Prof. Michael Lee'), ('Emily Davis', 'Dr. Emily Davis'), ('Robert Brown', 'Prof. Robert Brown'), ('Jessica Martinez', 'Dr. Jessica Martinez'), ('William Smith', 'Prof. William Smith'), ('Jennifer Wilson', 'Dr. Jennifer Wilson'), ('David Anderson', 'Prof. David Anderson'), ('Angela Thomas', 'Dr. Angela Thomas'), ('Christopher Harris', 'Prof. Christopher Harris')], default='Sarah Johnson', max_length=100)),
                ('description', models.TextField(max_length=500)),
            ],
        ),
    ]
